### ISSUE TITLE
Quesry on motor command

### ISSUE THREAD

**Issue by aravindSolteq** [MartinStokroos/nexus_base_ros#1]
Hey This is a nice project. Im interested to know what is the final cmd_motor that is being passed to motor. Im using a vesc controller for motor, Is this value the motor speed(erpm) or motor current or motor PWM duty cycle

**Comment by MartinStokroos** [comment]
Thank you for your interest in my project. _cmd_motor_ is indeed the PWM duty cycle. The message is a 4 element array of signed int16's. The mapping to the wheels is explained in the Arduino ino file.
