### ISSUE TITLE
rosserial arduino nodes and topics aren't listed

### ISSUE THREAD

**Issue by niklastimpe** [MartinStokroos/nexus_base_ros#4]
When i run `rosrun nexus_base_ros nexus_teleop_joy` (after roscore obviously) (there don't come any informations in the terminal) and the `rostopic list` or `rosnode list` the nodes and topics involved with the code on the arduino don't show of. 
But when i run, separately, `rosrun rosserial_python serial_node.py` the connection to the arduino works. Here the terminal output:

```
[INFO] [1626945121.098369]: ROS Serial Python Node
[INFO] [1626945121.110281]: Connecting to /dev/ttyUSB0 at 57600 baud
[INFO] [1626945123.221470]: Requesting topics...
[INFO] [1626945123.321866]: Note: publish buffer size is 128 bytes
[INFO] [1626945123.324969]: Setup publisher on wheel_vel [nexus_base_ros/Encoders]
[INFO] [1626945123.333704]: Setup service server on emergency_stop_enable [nexus_base_ros/EmergencyStopEnable]
[INFO] [1626945123.342398]: Setup service server on arming_enable [nexus_base_ros/ArmingEnable]
[INFO] [1626945123.351809]: Note: subscribe buffer size is 128 bytes
[INFO] [1626945123.355423]: Setup subscriber on cmd_motor [nexus_base_ros/Motors]

```

But although all nodes are listed now, with the exception that the arduino node is called serial_node, i can't use the robot, or publish anything to the robot.

What can I do?

PS: I removed the logitech controller node in the launch file, because i don't have one and want , as for now, to control the robot by separately publishing informations  from the terminal to the topics.

**Comment by MartinStokroos** [comment]
Hi,

The best thing you could do is to run `rqt_graph` and check if all nodes are up and connected to each other.
If your serial_node is up and subscribes to the relevant topics, it should connect.

**Comment by niklastimpe** [comment]
When i run the serial_node separately, it shows off but isn't connected to the nexus_teleop_joy node.

The nexus_teleop_joy and the serial_node are the only node active then.

When I write the Arduino code in the Arduino, I get this message: (maybe it has something to do with that?)



```
In file included from /home/niki/Desktop/catkin/src/nexus_base_ros/firmware/Nexus_Omni4WD_Rosserial/Nexus_Omni4WD_Rosserial.ino:77:0:
/home/niki/Arduino/libraries/digitalWriteFast/digitalWriteFast.h:25:0: warning: "digitalPinToTimer" redefined
 #define digitalPinToTimer(P) \
 
In file included from sketch/Nexus_Omni4WD_Rosserial.ino.cpp:1:0:
/home/niki/Documents/arduino-1.8.15-linux64/arduino-1.8.15/hardware/arduino/avr/cores/arduino/Arduino.h:180:0: note: this is the location of the previous definition
 #define digitalPinToTimer(P) ( pgm_read_byte( digital_pin_to_timer_PGM + (P) ) )
```

**Comment by niklastimpe** [comment]
I figured it out. I also needed to start the nexus_base_ros node separately and now all nodes are connected in the rqt_graph.
The only next problem is, that the motors don't spin when publishing something to a cmd_* node

**Comment by MartinStokroos** [comment]
The warning from digitalWriteFast is known to me. This does not cause any problems.
It might be that you need to send the 'arming' service message first. The LED should lit for a few seconds when the motors are enabled after sending a cmd message.
